<template>
  <div class="card" :class="{ selected: route.query.step === '7' }">
    <div class="card-header" @click="router.push({ ...route, query: { ...route.query, step: 7 } })">
      <div class="start">
        <span>7</span>
        <h3>{{ $t('cvResumeFile') }}</h3>
      </div>
      <div class="end">
        <div class="tag completed" v-if="userStore?.userData?.validProfileStatus?.resumeStatus">
          Completed
        </div>
        <div class="tag" v-else>Blank</div>
      </div>
    </div>
    <div class="card-body">
      <div class="form-fields">
        <div class="field">
          <label for="">{{ $t('Build / Upload Your CV') }}<span>*</span></label>
          <div class="control">
            <div class="cv-option">
              <p :class="{ selected: !resumeStore.vipoCVStatus }"
                @click="() => { resumeStore.vipoCVStatus = false; changeCVStatus() }">
                <span></span> {{ $t('cvAlreadyHaveCv') }}
              </p>
              <p :class="{ selected: resumeStore.vipoCVStatus }" @click="() => {
                resumeStore.vipoCVStatus = true; changeCVStatus()
              }">
                <span></span> {{ $t('cvPleaseBuildMyCv') }}
              </p>
            </div>
          </div>
        </div>
        <div class="field" style="margin-bottom: 0" v-if="!resumeStore.vipoCVStatus">
          <label for="">{{ $t('cvPleaseSelectAFile') }}<span>*</span></label>
          <div class="control">
            <label for="cv-file" class="uploader">
              <i class="fa-regular fa-arrow-up"></i>
              <p>{{ $t('cvOnlyPDFWordAndJPGFilesAreAcceptedWithAMaximumFileSizeOf5MB') }}</p>
              <input type="file" id="cv-file" ref="cvFileRef" @change="onCVFileChange" />
            </label>
            <br />
          </div>
          <p v-if="resumeStore?.cv?.name && !resumeStore?.cv?.src">{{ resumeStore?.cv?.name }}</p>
          <a :href="resumeStore?.cv?.src" target="_blank" class="button gen-cv-button orange"
            v-if="resumeStore?.cv?.src">
            <i class="fa-regular fa-file-pdf"></i>
            {{ $t('cvDownloadCvFile') }}
          </a>
        </div>
        <div class="checklist" v-show="resumeStore.vipoCVStatus">
          <p :class="{ green: isReady, red: !isReady }" v-for="i in checkCVStatusReadyGenerate(
            userStore?.userData?.validProfileStatus)">
            <i class="fa-solid fa-circle-xmark"></i>{{ i }}
          </p>
        </div>

        <div class="field" v-if="resumeStore.vipoCVStatus && resumeStore?.cv?.src">
          <label for="">{{ $t('CV generated by the system') }}<span>*</span></label>
          <div class="control">
            <a class="file-name" :href="resumeStore?.cv?.src" target="_blank" style="cursor: pointer"
              v-if="resumeStore?.cv?.src">
              <button class="button gen-cv-button black" target="_blank">
                {{ $t('cvDownloadCvFile') }}
              </button></a>
          </div>
        </div>
        <div v-if="resumeStore.error || resumeStore.cvError">
          <p class="red" v-if="resumeStore.cvError">
            {{ $t(resumeStore.cvError) }}
          </p>
          <p class="red" v-if="resumeStore.error">
            {{ $t(resumeStore.error) }}
          </p>
        </div>
      </div>


      <div class="button-group">
        <a></a>
        <button class="button orange" @click="submitForm()" v-if="!resumeStore.vipoCVStatus">
          {{ $t('Save') }}
        </button>
        <button class="button orange" @click="submitForm()" v-else
          :disabled="!checkValidateGenerateCV && resumeStore.vipoCVStatus">
          {{ $t('Create CV') }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">

import useFetchCustom from '~/utils/global-useFetch'
import { useResumeStore } from '@/store/resume'
import { useRoute, useRouter } from 'vue-router'
const route = useRoute()
const router = useRouter()
const resumeStore = useResumeStore()

import { useUserStore } from '@/store/user'
const userStore = useUserStore()

import { useI18n } from 'vue-i18n'
const { t } = useI18n()

const isNextdotEvent = ref<any>(false)
const isAppliedNextdot = ref<any>(false)

const checkValidateGenerateCV = ref<any>(false)
const checkWiiFairValidate = ref<boolean>(false)


const changeCVStatus = async () => {
  if (userStore?.seekerInfo) {
    const i = userStore?.seekerInfo
    resumeStore.setFieldValue('cv', null) //Set null first

    if (i?.cv?.src && !resumeStore?.vipoCVStatus) {
      resumeStore.setFieldValue('cv', i.cv)
      resumeStore.cv.name = i.cv?.link?.split('/').pop()
    }
    if (i.vipoCV?.src && resumeStore.vipoCVStatus) {
      resumeStore.setFieldValue('cv', i.vipoCV)
      resumeStore.cv.name = ''
    }
  }
}

watch(() => userStore?.seekerInfo, async (value: any) => {

  if (userStore?.seekerInfo) {
    const i = userStore?.seekerInfo

    if (i?.cv?.src && !i?.vipoCVStatus) {
      resumeStore.setFieldValue('cv', i.cv)
      resumeStore.cv.name = i.cv?.link?.split('/').pop()
    }
    if (i.vipoCV?.src && i?.vipoCVStatus) {
      resumeStore.setFieldValue('cv', i.vipoCV)
      resumeStore.cv.name = ''
    }
    resumeStore.setFieldValue('vipoCVStatus', i.vipoCVStatus)
  }
}, { immediate: true })



const onCVFileChange = async ($event: any) => {
  const file = $event.target.files[0]
  const formData = new FormData()
  formData.append('file', file)

  const { data, error } = await useFetchCustom('/upload-resume').post(formData).json()

  if (data.value) {
    resumeStore.cv = data.value.myFile
    resumeStore.checkUploadResume = true
  }
}

const isReady = ref<any>(false)


const checkCVStatusReadyGenerate = (item: any) => {
  if (!item) {
    isReady.value = false
    return ''
  }

  const profileStatus = {
    educationStatus: item.educationStatus,
    languageStatus: item.languageStatus,
    personalInformationStatus: item.personalInformationStatus,
    skillStatus: item.skillStatus,
    workHistoryStatus: item.workHistoryStatus,
    workPreferenceStatus: item.workPreferenceStatus
  }

  const messages: Record<string, string> = {
    personalInformationStatus: 'personalInformationStatus',
    educationStatus: 'educationStatus',
    workHistoryStatus: 'workHistoryStatus',
    skillStatus: 'skillStatus',
    languageStatus: 'languageStatus',
    workPreferenceStatus: 'workPreferenceStatus'
  }

  const result = Object.entries(profileStatus)
    .filter(([_, value]) => value === false)
    .map(([key], index) => ` ${t(messages[key])}`)

  isReady.value = result.length === 0
  return result.length ? result : [t('ready To Generate')]
}

const checkPersonalAndWorkPreferenceReady = (item: any) => {
  if (!item) {
    isReady.value = false
    return ''
  }

  const profileStatus = {
    personalInformationStatus: item.personalInformationStatus,
    workPreferenceStatus: item.workPreferenceStatus
  }

  const messages: Record<string, string> = {
    personalInformationStatus: 'personalInformationStatus',
    workPreferenceStatus: 'workPreferenceStatus'
  }

  const result = Object.entries(profileStatus)
    .filter(([_, value]) => value === false)
    .map(([key], index) => ` ${t(messages[key])}`)

  isReady.value = result.length === 0
  return result.length ? result : [t('ready To Generate')]
}

const submitForm = async () => {

  await resumeStore.submitStep7Form()
  await userStore.fetchSeekerInfo()
  await userStore.fetchUserInfo()
  const step = Math.min(Number(route.query.step) + 1 || 2, 7)
  router.push({ query: { ...route.query, step: String(step) } })
}

//Check Validate field step by step first generate CV
watch(() => userStore?.userData?.validProfileStatus, (value: any) => {
  if (!value) { return }
  const profileStatus: any = {
    educationStatus: value.educationStatus,
    languageStatus: value.languageStatus,
    personalInformationStatus: value.personalInformationStatus,
    skillStatus: value.skillStatus,
    workHistoryStatus: value.workHistoryStatus,
    workPreferenceStatus: value.workPreferenceStatus
  }

  const isAllStatusComplete = Object.values(profileStatus).every(
    (status) => status === true
  )
  checkValidateGenerateCV.value = isAllStatusComplete
  //Check personalInfoAndWorkpreference 
  const personalStatusAndWorkPreference: any = {
    personalInformationStatus: value.personalInformationStatus,
    workPreferenceStatus: value.workPreferenceStatus
  }

  const isPersonalAndWorkPreferenceComplete = Object.values(personalStatusAndWorkPreference).every(
    (status) => status === true
  )
  checkWiiFairValidate.value = isPersonalAndWorkPreferenceComplete

}, { immediate: true })

</script>

<style scoped lang="scss">
.uploader {
  background-color: var(--primary-100);
  box-shadow: 0 0 0 2px var(--primary-500);
  border-radius: 12px;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  padding: 1.5rem;
  max-width: 200px;
  margin-top: 10px;

  i {
    font-size: 1em;
    margin-bottom: 0.75em;
    width: 40px;
    height: 40px;
    border-radius: 999px;
    background-color: var(--primary-500);
    color: #fff;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  p {
    font-size: var(--xsm-font);
    color: var(--black-600);
    text-align: center;
    font-weight: 500;
  }

  input {
    display: none;
  }
}

.cv-option {
  margin-top: 0.5em;
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 0.5rem;

  @media screen and (min-width: 1024px) {
    flex-direction: row;
  }

  p {
    border: 1px solid var(--black-300);
    display: flex;
    align-items: center;
    gap: 0.5em;
    cursor: pointer;
    padding: 0.75em;
    border-radius: 12px;

    span {
      min-width: 25px;
      min-height: 25px;
      max-width: 25px;
      max-height: 25px;
      border-radius: 999px;
      border: 2px solid var(--black-300);
      display: block;
      position: relative;
    }

    &.selected {
      span {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        border: 2px solid var(--primary-500);

        &::before {
          content: '';
          position: absolute;
          width: 13px;
          height: 13px;
          border-radius: 999px;
          background-color: var(--primary-500);
          z-index: 9;
        }
      }
    }
  }
}

.checklist {
  border: 1px solid var(--red-500);
  padding: 1em;
  border-radius: 12px;
  margin-bottom: 1em;

  p {
    line-height: 2;
    display: flex;
    align-items: flex-start;
    gap: 0.25em;
    color: var(--red-500);

    i {
      position: relative;
      top: 8px;
    }
  }
}

.file-name {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

button {
  display: inline-block;
}

.cv-file {
  margin-bottom: 10px;
  display: inline-flex;
  align-items: center;
  background-color: var(--black-100);
  padding: 0 1rem;
  border-radius: 8px;
  cursor: pointer;
  height: 3rem;
  color: var(--primary-500);

  a {
    display: -webkit-box;
    -webkit-line-clamp: 1;
    /* number of lines */
    -webkit-box-orient: vertical;
    overflow: hidden;
  }

  p {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  span {
    margin-left: auto;

    i {
      font-size: var(--sm-font);
      color: var(--red-900);
    }
  }
}

.gen-cv-button {
  margin-top: 10px;
  display: inline-flex;
  align-items: center;
  height: 2.8em;

  i {
    display: none;
  }

  &.loading {
    i {
      margin-right: 0.5em;
      display: inline-block;
      animation: spinCW 1s linear infinite;
    }
  }

  @keyframes spinCW {
    0% {
      transform: rotate(0deg);
    }

    /* start */
    100% {
      transform: rotate(360deg);
    }

    /* end → clockwise */
  }
}
</style>
